### ISSUE TITLE
Front-end app example in React

### ISSUE THREAD

**Issue by imagobea** [maticnetwork/nightfall-sdk#115]
We have decided to migrate the front-end app to React.

### MVP

- [x] Prototype React app (keep an eye on dependencies audit)
- [x] Replace `scripts/webApp` with new project
- [x] Add SDK as dependency using `"nightfall-sdk": "file:../../"`
- [x] Update npm script `eg:web-app`
- [ ] Update README (both SDK and app)

### App requirements

**MUST**

- [x] Consume env vars from file (this is currently managed from a [config file](https://github.com/maticnetwork/nightfall-sdk/blob/master/examples/webApp/src/config.ts))
- [x]  Show Nightfall thumbnail (grab the svg from dir [public](https://github.com/maticnetwork/nightfall-sdk/tree/master/examples/webApp/public))
- [x]  Create an instance of `User` upon landing (see [Home component](https://github.com/maticnetwork/nightfall-sdk/blob/master/examples/webApp/src/views/Home.vue), create a handle for monitoring MetaMask account changes
- [x]  Allow user to perform hardcoded deposit (see [HelloWorld](https://github.com/maticnetwork/nightfall-sdk/blob/master/examples/webApp/src/components/HelloWorld.vue) component)
- [x] Page displays nightfall balance

**SHOULD** (could be separate issue)

- [x]  Allow user to perform transfer, withdrawal
- [x]  Refresh balance after each deposit
- [ ] Allow for dynamic values e.g. token address - if these are hard-coded you have to modify the code-base when switching networks
- [ ] Finalise withdrawal

**COULD** (create separate issues)

- [x] Look nicer!!
- [x] Have an About page to link to README, official Matic docs, include a list of project ideas for Hackathons, etc.

**Comment by velkoskis** [comment]
- [ ] Consume env vars from file (this is currently managed from a config file)
- [ ] Show Nightfall thumbnail (grab the svg from dir public)
- [ ] Create an instance of User upon landing (see Home component, create a handle for monitoring MetaMask account changes
- [ ] Allow user to perform hardcoded deposit (see HelloWorld component)
- [ ] Page displays nightfall balance

**Comment by velkoskis** [comment]
This is a separate issue:
-  Look nicer!!
-  Have an About page to link to README, official Matic docs, include a list of project ideas for Hackathons, etc.

**Comment by velkoskis** [comment]
This is a separate issue too!
Allow for dynamic values e.g. token address - if these are hard-coded you have to modify the code-base when switching networks
 Finalise withdrawal

https://app.zenhub.com/workspaces/pnf-6295dbd03832a40014480c20/issues/maticnetwork/nightfall-sdk/130
