### ISSUE TITLE
Refactor example scripts for SDK and update Readme

### ISSUE THREAD

**Issue by ghost** [maticnetwork/nightfall-sdk#118]
Currently the are a lot of example scripts in the SDK. By covering each functionality for each token standard we end up having 16+ different example scripts.

Goal: Create a single script per functionality for all standards

- [x] Create a single script for deposit
- [x] Create a single script for transfer
- [x] Create a single script for withdrawal
- [x] Create a single script for finaliseWithdrawal

Refactor the list of scripts as it is getting too long.

Documentation:

- [ ] update readme

**Comment by velkoskis** [comment]
Deposit ERC721 connection is not closing. Fix the issue within this ticket after ERC1155 implementation.

**Comment by velkoskis** [comment]
Documentation for all 3 token standards!
