### ISSUE TITLE
Migrate from web3 to ethers

### ISSUE THREAD

**Issue by imagobea** [maticnetwork/nightfall-sdk#123]
Creating a ticket for this migration. Adding `question` label to check with @signorecello @daveroga @israelboudoux - I think the migration is worth it for consistency across repos, but that's my opinion. If you agree, please move this to whatever column you see fit, otherwise just close the issue.

**Comment by signorecello** [comment]
I think it makes total sense to be as consistent as possible. So yes

**Comment by imagobea** [comment]
Not happening
