### ISSUE TITLE
Create NPM package for User SDK

### ISSUE THREAD

**Issue by imagobea** [maticnetwork/nightfall-sdk#25]
See original issue in [nightfall_3 #452](https://github.com/EYBlockchain/nightfall_3/issues/452).

Review Package.json

- [x] Package name
- [x] License
- [x] Version

**Comment by imagobea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PNF-6295dbd03832a40014480c20/issues/maticnetwork/nightfall-sdk/25?planning-poker) with ZenHub @imagobea @luizoamorim

**Comment by luizoamorim** [comment]
# Some questions

1. Should we user some specific npmjs account. Like, using nightfall general email?
2. Package name?
  - @nigthfall3/sdk ? (Scoped public)
  - nightfall3-sdk ? (public)
  - nightfall3 ?
  - other suggestions ...

3. Version?
  - 1.0.0?

**Comment by imagobea** [comment]
1. Absolutely, we shouldn't publish from a generic account
2. We discussed with @druiz0992 some time ago and we agreed not to use scopes, we could use `nightfall-sdk`
3. Perhaps we can start with 0.0.1 and move to 1.0.0 when we have all ERCs and Metamask capabilities
4. Licensing is also important. Nightfall_3 uses creative commons but I don't think that is enough to make the code open source.

**Comment by luizoamorim** [comment]
1. Have we already some email for the team to be used for that?
2. Nice. So nightfall-sdk.
3. IMO either 1.0.0 or 0.1.0. If you start with 0.0.1 looks like we're starting with some bug. Not a feature or release.
  - From now we need to understand better what should be features that will increment our patch when merged with master.
  - Also what tasks are bugs to increment the minor.
4. For that is just choose one and put the license in package.json? I don't know very well how this part works.

**Comment by imagobea** [comment]
1. So hopefully we will get some feedback on Slack
3. Let's check with davids, for me 0.1.0 is good but maybe they also agree on 1.0.0
4. It's exactly that - choosing one and updating the package.json, let's find out together

**Comment by imagobea** [comment]
We made it!!
https://www.npmjs.com/package/nightfall-sdk
