### ISSUE TITLE
Repo `nightfall-sdk` README

### ISSUE THREAD

**Issue by imagobea** [maticnetwork/nightfall-sdk#26]

**Comment by imagobea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PNF-6295dbd03832a40014480c20/issues/maticnetwork/nightfall-sdk/26?planning-poker) with ZenHub @imagobea @luizoamorim

**Comment by VelkoskiS** [comment]
This documentation should be aligned with the plans and releases for early September?

**Comment by velkoskis** [comment]
- [ ] Improve libs/user/user.ts ie UserFactory but specially methods in User class with JSDocs

- [ ] SHORT + INLINE comments on scripts on top of the different key steps

- [ ] README notes explaining context for the scripts
