### ISSUE TITLE
Review User SDK example scripts

### ISSUE THREAD

**Issue by imagobea** [maticnetwork/nightfall-sdk#27]
Final look at User SDK example scripts.

Replaces [nightfall_3 #703](https://github.com/EYBlockchain/nightfall_3/issues/703).

**Comment by imagobea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PNF-6295dbd03832a40014480c20/issues/maticnetwork/nightfall-sdk/27?planning-poker) with ZenHub @imagobea @luizoamorim

**Comment by velkoskis** [comment]
Test mainnet after depolyments.

**Comment by imagobea** [comment]
Hello @velkoskis
Thank you for your comment!

I think for now it will be enough to double-check testnet Goerli. For this purpose I created #77.

On the other hand, I believe we have probably gone enough times through the example scripts. If you agree, please close this issue. Thank you! :pray

**Comment by velkoskis** [comment]
Thank you for opening the the issue @imagobea . I agree, closing this issue.
