### ISSUE TITLE
Review web3Websocket

### ISSUE THREAD

**Issue by imagobea** [maticnetwork/nightfall-sdk#39]
File `web3Websocket.ts` contains the logic for managing a blockchain connection via websocket. Includes:

- A "config object" `WEB3_PROVIDER_OPTIONS` passed when connecting - see `new Web3.providers.WebsocketProvider(...)`
- A method that continuously checks if the provider is no longer connected (in which case will try to reconnect) - see `checkWsConnection`
- A method that continuously asks for the latest block number, possibly to keep connection alive - see `refreshWsConnection`

### Task

- [ ] Review how those options and methods play together, address redundancies/inconsistencies

### Other considerations

Pls see this ticket [nightfall_3 #495](https://app.zenhub.com/workspaces/pnf-6295dbd03832a40014480c20/issues/eyblockchain/nightfall_3/495)

### Docs

https://web3js.readthedocs.io/en/v1.7.3/web3.html#providers

**Comment by imagobea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PNF-6295dbd03832a40014480c20/issues/maticnetwork/nightfall-sdk/39?planning-poker) with ZenHub @daveroga @imagobea @israelboudoux @luizoamorim

**Comment by imagobea** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PNF-6295dbd03832a40014480c20/issues/maticnetwork/nightfall-sdk/39?planning-poker) with ZenHub @daveroga

**Comment by daveroga** [comment]
Waiting for Make for Issue `Proposer and Optimist sockets more aware of each other#665` to be finished to proceed with this

**Comment by imagobea** [comment]
Not worth our time since we will move to `ethers` library soon.
