### ISSUE TITLE
Provide support for ERC1155

### ISSUE THREAD

**Issue by imagobea** [maticnetwork/nightfall-sdk#54]
Issue #14 covered ERC20 use case for simplicity. This issue is for extending SDK support to token standard ERC1155.

The requirement is for the user to be able to transact (deposit, transfer, withdraw) tokens using this standard.

See #32 for more information about the task at hand.

**Comment by velkoskis** [comment]
- [ ] Research ERC1155 Standard
- [ ]  Deploy and verify ERC1155Mock to Goerli
- [ ] Implement 1155 onto the current ERC20 and ERC1155 implementation
- [ ] Add example script for 1155
- [ ]  Refactor example scripts to 4 files. ERC20, ERC721, ERC1155
