### ISSUE TITLE
Enable zkpKeys generation from mnemonic

### ISSUE THREAD

**Issue by luizoamorim** [maticnetwork/nightfall-sdk#61]
### Context

To interact with Nightfall, you need a set of Zero-knowledge proof keys (zkpKeys). Today this set can be generated via the client API (`nightfall-client`), by making a POST request to `/generate-zkp-keys`, passing a valid bip39 `mnemonic` + `addressIndex`.

### What we are trying to achieve

Recreate the logic for generating the zkpKeys in the SDK to avoid sending the mnemonic via HTTP.

### References

**When/where are zkpKeys managed in the SDK?** 

- Look in libs/user/user.ts `UserFactory`. Keys are generated when creating an instance of `User`.
- Logic is concentrated in libs/nightfall/keys.ts `createZkpKeysAndSubscribeToIncomingKeys`. It is a 3-step process: 1) create/validate bip39 mnemonic, 2) generate zkpKeys via client, 3) subscribe to incoming keys via client. We need to refactor step 2.

**When/where are zkpKeys managed in nightfall_3?**

- See nightfall_3/nightfall-client/src/services/keys.mjs

### On hold

Development paused since keys file has dependencies with common-files (poseidon and curves).

Once ZkpKeys logic is available on SDK, we should consider opening an issue for validating nightfall addresses upon transfer:

```js
ZkpKeys.decompressZkpPublicKey(generalise(recipient))
```

**Comment by imagobea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PNF-6295dbd03832a40014480c20/issues/maticnetwork/nightfall-sdk/61?planning-poker) with ZenHub @velkoskis @luizoamorim

**Comment by imagobea** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PNF-6295dbd03832a40014480c20/issues/maticnetwork/nightfall-sdk/61?planning-poker) with ZenHub @imagobea
